---
spring:
  application:
    name: couch-potato-test-service
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/db?currentSchema=public&logUnclosedConnections=true
    username: dbuser
    password: dbpassword
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    open-in-view: false
    database: postgresql
    properties:
      hibernate:
        default_schema: public
        order_updates: true
        generate_statistics: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  task:
    execution:
      pool:
        allow-core-thread-timeout: true
        core-size: 8
        max-size: 2147483647
        queue-capacity: 2147483647
        keep-alive: 60s
  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include: "*"
    enabled-by-default: true
  tracing:
    enabled: true
    propagation:
      type: w3c
    sampling:
      probability: 1
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

jdbc:
  datasource-proxy:
    query:
      enable-logging: true
      log-level: debug
      logger-name: query-logger
    include-parameter-values: true
    logging: slf4j
    slow-query:
      enable-logging: true
